version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
